/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutUsRouteImport } from './routes/about-us'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as LeadershipRouteImport } from './routes/leadership'
import { Route as OurProjectsIndexRouteImport } from './routes/our-projects.index'
import { Route as OurProjectsSlugRouteImport } from './routes/our-projects.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutUsRoute = AboutUsRouteImport.update({
  id: '/about-us',
  path: '/about-us',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadershipRoute = LeadershipRouteImport.update({
  id: '/leadership',
  path: '/leadership',
  getParentRoute: () => rootRouteImport,
} as any)
const OurProjectsIndexRoute = OurProjectsIndexRouteImport.update({
  id: '/our-projects/',
  path: '/our-projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const OurProjectsSlugRoute = OurProjectsSlugRouteImport.update({
  id: '/our-projects/$slug',
  path: '/our-projects/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/contact': typeof ContactRoute
  '/leadership': typeof LeadershipRoute
  '/our-projects/$slug': typeof OurProjectsSlugRoute
  '/our-projects/': typeof OurProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/contact': typeof ContactRoute
  '/leadership': typeof LeadershipRoute
  '/our-projects/$slug': typeof OurProjectsSlugRoute
  '/our-projects': typeof OurProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/contact': typeof ContactRoute
  '/leadership': typeof LeadershipRoute
  '/our-projects/$slug': typeof OurProjectsSlugRoute
  '/our-projects/': typeof OurProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about-us'
    | '/contact'
    | '/leadership'
    | '/our-projects/$slug'
    | '/our-projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about-us'
    | '/contact'
    | '/leadership'
    | '/our-projects/$slug'
    | '/our-projects'
  id:
    | '__root__'
    | '/'
    | '/about-us'
    | '/contact'
    | '/leadership'
    | '/our-projects/$slug'
    | '/our-projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutUsRoute: typeof AboutUsRoute
  ContactRoute: typeof ContactRoute
  LeadershipRoute: typeof LeadershipRoute
  OurProjectsSlugRoute: typeof OurProjectsSlugRoute
  OurProjectsIndexRoute: typeof OurProjectsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-us': {
      id: '/about-us'
      path: '/about-us'
      fullPath: '/about-us'
      preLoaderRoute: typeof AboutUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leadership': {
      id: '/leadership'
      path: '/leadership'
      fullPath: '/leadership'
      preLoaderRoute: typeof LeadershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-projects/': {
      id: '/our-projects/'
      path: '/our-projects'
      fullPath: '/our-projects/'
      preLoaderRoute: typeof OurProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-projects/$slug': {
      id: '/our-projects/$slug'
      path: '/our-projects/$slug'
      fullPath: '/our-projects/$slug'
      preLoaderRoute: typeof OurProjectsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutUsRoute: AboutUsRoute,
  ContactRoute: ContactRoute,
  LeadershipRoute: LeadershipRoute,
  OurProjectsSlugRoute: OurProjectsSlugRoute,
  OurProjectsIndexRoute: OurProjectsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
